#!/bin/sh

wrap_pacman() {
  sudo pacman -S --needed - < ${1}
}

main() {
  sudo pacman -Syu
  wrap_pacman ../pacman-packages/bull-packages.txt
  wrap_pacman ../pacman-packages/gtk-packages.txt
  wrap_pacman ../pacman-packages/x-packages.txt
  wrap_pacman ../pacman-packages/programming-packages.txt
  sudo pacman -S --needed --asdeps - < ../pacman-packages/dependent-packages.txt
}

main "$@"
