#!/bin/sh -eu

# The directory holding your source code and Cabal file:
SRC_DIR=~/.config/xmonad/
EXE_NAME=xmonad-config
output_file=$1; shift

cd $SRC_DIR

cabal new-configure \
      --enable-optimization \
      --enable-executable-stripping

cabal new-build

find dist-newstyle -type f -executable -name $EXE_NAME \
     -exec mv -u '{}' $output_file ';'
