#! /bin/sh

year=$(date '+%Y')
month=$(date '+%m')

case "$BLOCK_BUTTON" in
  1|2)
    date=$(date '+%A, %d. %B');;
  3)
    (( month == 12 )) && month=1 && year=$((year + 1)) || month=$((month + 1))
    date=$(cal $month $year | sed -n '1s/^  *//;1s/  *$//p')
esac

case "$BLOCK_BUTTON" in
  1|2|3)
    export TERM=xterm
    cal --color=always $month $year \
      | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
      | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
      | tail -n +2 \
      | rofi \
      -dmenu \
      -markup-rows \
      -no-fullscreen \
      -hide-scrollbar \
      -bw 1 \
      -eh 1 \
      -location 3 \
      -width -22 \
      -lines 6 \
      -fixed-num-lines 6 \
      -no-custom \
      -p "$date" > /dev/null
esac

DATEFMT="+%a,%d %b %Y"
blockdate=$(date "$DATEFMT")
echo "  $blockdate"
