require'lspkind'.init{
  with_text = true,
  preset = 'default',
  symbol_map = {
    Text          = "",
    Method        = "ƒ",
    Function      = "",
    Constructor   = "",
    Field         = " ",
    Variable      = "",
    Class         = "",
    Interface     = "蘒",
    Module        = "",
    Property      = "",
    Unit          = "塞",
    Value         = "",
    Enum          = "練",
    Keyword       = "",
    Snippet       = "זּ",
    Color         = "",
    File          = "",
    Folder        = "ﱮ",
    EnumMember    = "",
    Constant      = "",
    Struct        = "",
    Event         = "",
    Operator      = "",
    TypeParameter = "<>",
  },
}
