let g:webdevicons_enable                      = 1
let g:webdevicons_enable_nerdtree             = 0
let g:webdevicons_conceal_nerdtree_brackets   = 0
let g:WebDevIconsNerdTreeGitPluginForceVAlign = 0
let g:WebDevIconsNerdTreeAfterGlyphPadding    = ' '
let g:webdevicons_enable_unite                = 0
let g:webdevicons_enable_vimfiler             = 0
let g:webdevicons_enable_airline_tabline      = 1
let g:webdevicons_enable_airline_statusline   = 1
let g:WebDevIconsTabAirLineAfterGlyphPadding  = ''
let g:WebDevIconsTabAirLineBeforeGlyphPadding = ' '
let g:webdevicons_enable_ctrlp                = 0
let g:webdevicons_enable_startify             = 1
let g:webdevicons_enable_flagship_statusline  = 0
let g:webdevicons_enable_denite               = 0

let g:WebDevIconsUnicodeDecorateFileNodes = 1
let g:WebDevIconsUnicodeGlyphDoubleWidth = 1

let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1
let g:DevIconsEnableFolderPatternMatching = 1
let g:DevIconsEnableFolderExtensionPatternMatching = 0
let WebDevIconsUnicodeDecorateFolderNodesExactMatches = 0

let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols         = {}
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['tex']  = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['pdf']  = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['epub'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['html'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['css']  = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['js']   = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['png']  = ' '
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['jpg']  = ' '
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['jpeg'] = ' '
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['mp3']  = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['mp4']  = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['out']  = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['toml'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['lock'] = ''
